### ISSUE TITLE
AI Navigation side menu not working

### ISSUE THREAD

**Issue by auhrick** [mieweb/docs#41]
The document "AI Chat Box" was published and I can search and locate it in the online help:

![image](https://github.com/user-attachments/assets/35a14112-358f-4e87-b8ee-44f33a2fde43)

However, if I use the Navigation bar, I am not able to go to the document and I am redirected back to the starting online help page.

![image](https://github.com/user-attachments/assets/51384a71-dcae-422d-8526-b0ca34344345)

I am able to navigate to other documents in other sections.

**Comment by ggodlewski** [comment]
Awaiting @horner to approve above hotfix

**Comment by monpie3** [comment]
We encountered similar problem with "Whisper AI - Dictation - Summarize" sub-tab under the Artificial intelligence tab.
![image](https://github.com/user-attachments/assets/7e688151-0f9b-45e1-8616-e5e56c951f0a)

We try to solve it by republishing `navigation.md`, `toc.md` and the document itself, but now it doesn't show up in the navigation at all (but it can still be searched -> https://docs.enterprisehealth.com/functions/artificial-intelligence/whisper-ai-dictation-summarize/#search=whisper)

Not sure what I'm missing:
toc.md: https://github.com/mieweb/docs/blob/master/content/toc.md
navigation.md: https://github.com/mieweb/docs/blob/master/content/navigation.md 
whisper-ai-dictation-summarize.md: https://github.com/mieweb/docs/blob/master/content/functions/artificial-intelligence/whisper-ai-dictation-summarize.md#whisper-ai
artificial-intelligence.md:  https://github.com/mieweb/docs/blob/master/content/functions/artificial-intelligence.md

Looking at the files, I believe the tab should show up. I don't see any uncommitted changes on wikigdrive related to this. Please let me know if I missed anything.

**Comment by ggodlewski** [comment]
@monpie3 https://github.com/mieweb/docs/actions/runs/11385099396/job/31674213039
![image](https://github.com/user-attachments/assets/9e6a6079-96a9-48bb-be9d-3fb621b346c7)

**Comment by ggodlewski** [comment]
Should be fixed but I don't have access to https://docs-qa.med-web.com/45-merge/ so I can't verify it.

**Comment by monpie3** [comment]
![image](https://github.com/user-attachments/assets/ec78a775-f7a7-4171-a78e-8519219e6e37)

I checked [https://docs-qa.med-web.com/45-merge/](https://docs-qa.med-web.com/45-merge/), and unfortunately, that sub-tab still isn't showing up there.

**Comment by monpie3** [comment]
It is now working correctly on https://docs-qa.med-web.com/45-merge/ I approved PR, but I'm not authorized to merge it. 

![image](https://github.com/user-attachments/assets/bf8bbdad-316e-4cf2-a247-9707b11c3a95)
